name: CI Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  html-lint:
    name: HTML Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install htmlhint

      - name: Run HTMLHint
        run: npx htmlhint "index.html" --config .htmlhintrc

  css-lint:
    name: CSS Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install stylelint stylelint-config-standard

      - name: Run Stylelint
        run: npx stylelint "style/**/*.css" --config .stylelintrc.json

  js-lint:
    name: JS Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install eslint @eslint/js globals

      - name: Run ESLint
        run: npx eslint "script/**/*.js"

